# Stage 1: Builder
FROM registry.access.redhat.com/ubi8/nodejs-18 as builder

# Set working directory
WORKDIR /app

USER root

# Install git and clean up
RUN dnf install -y git && dnf clean all

# Clone the repo
RUN git clone https://github.com/meta-llama/llama-stack.git .

# Set working directory to the TypeScript UI folder
WORKDIR /app/llama_stack/ui

# Change ownership to user 1001
RUN chown -R 1001:1001 /app/llama_stack/ui

USER 1001

# Install TypeScript dependencies and build the app
RUN npm install 

EXPOSE 8322

# Use non-root user


# Launch the TypeScript app
CMD ["npm", "run", "dev"]